---
title: "Meagan Capstone"
author: "Meagan Brown"
date: "2023-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Load Libraries
```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(fasterize)
```

```{r}
# set working directory
setwd(here('~', 'meds', 'capstone', 'aquafire'))
```

## Load Boundaries
```{r}
# Load in ecoregions shapefile
eco_regions <- read_sf(here::here('data', 'ca_eco_l3')) %>% 
  janitor::clean_names()  %>% 
  st_transform("EPSG: 3310") %>% 
  rename(region = us_l3name)

# Read in CA county boundaries
ca_counties <- read_sf(here::here('data', 'CA_Counties')) %>% 
  janitor::clean_names() %>% 
  st_transform("EPSG: 3310") # NAD28 / California Albers

# Filter sb county
sb_county <- ca_counties %>% 
  filter(name == "Santa Barbara")
```

## Load GDE Data
```{r}
veg_layer <- st_read(dsn = here('data', 'i02_NaturalCommunitiesCommonlyAssociatedwithGroundwater_v2_0.gdb'),
                     layer = 'i02_NCCAG_Vegetation_2_0') %>% 
  st_transform("EPSG: 3310")

wetland_layer <- st_read(dsn = here('data', 'i02_NaturalCommunitiesCommonlyAssociatedwithGroundwater_v2_0.gdb'),
                     layer = 'i02_NCCAG_Wetlands_2_0')

wetland_layer <- wetland_layer %>% 
  mutate('val' = 1)

gde <- gde %>% 
  mutate('val' = 1)

ca <- st_crop(gde_veg, ca_counties) %>%
  mutate(val = 1)

ca_ext <- extent(ca)
ca_rast <- raster(ca_ext, resolution = 30) # check that this is 30 *meters* 
crs(ca_rast) <- "+init=epsg:3310" # set crs

fasterize(st_collection_extract(gde_layer, "LINESTRING"), ca_rast, field = 'val', background = 0)

fasterize(gde_layer, ca_rast, field = "val", fun="sum")

gde_raster <- fasterize(sf = gde_layer,
                        raster = ca_rast,
                        field = NULL,
                        fun = "count")

# # read in groundwater dependent ecosystem shapefile + clean names
# gde_veg <- read_sf(here('data',
#                         'i02_naturalcommunitiescommonlyassociatedwithgroundwater',
#                         'i02_NCCAG_Vegetation.shp')) %>%
#   clean_names() %>%
#   st_transform("EPSG: 3310") # NAD28 / California Albers
# 
# gde_wetlands <- read_sf(here('data','i02_naturalcommunitiescommonlyassociatedwithgroundwater','i02_NCCAG_Wetlands.shp')) %>%
#   clean_names()  %>%
#   st_transform("EPSG: 3310") # NAD28 / California Albers
# 
# gde <- st_join(gde_veg, gde_wetlands)
# 
# gde_ndvi <- st_read(here('data', 'i02_NaturalCommunitiesCommonlyAssociatedwithGroundwater_v2_0.gdb')) %>% 
#   st_transform("EPSG: 3310") %>% 
#   clean_names() %>% 
#   st_cast(gde_ndvi, "MULTIPOLYGON")
```

## Load Fire Data
```{r}
fire_perimeters_all <- sf::read_sf(here('data', 
                                        'California_Fire_Perimeters_all')) %>% 
  clean_names() %>% 
  st_transform("EPSG: 3310") # NAD28 / California Albers
```

## Burn Severity
```{r}
#load libraries
library(tidyverse)
library(dplyr)
library(here)
library(janitor)
library(tmap)
library(stars)
library(gridExtra)
library(raster)
library(terra)
```


```{r}
# Load the necessary library
library(terra)

# Define the directory where the raster files are located
raster_dir <- here::here("data", "MTBS_BSmosaics")

# Define the target CRS
target_crs <- "EPSG:3310"

# Get a list of .tif files in the directory
tif_files <- list.files(raster_dir, pattern = "\\.tif$", full.names = TRUE)

# Initialize the raster stack variable
raster_stack <- NULL

# Loop through the files
for (file_path in tif_files) {
  # Print a message to the console
  message("Processing file: ", file_path)

  # Read the raster file
  raster <- rast(file_path)
  
  # Project the raster to the target CRS
  raster_new_crs <- project(raster, target_crs)
  
  # If this is the first file, initialize the raster stack
  if (is.null(raster_stack)) {
    raster_stack <- raster_new_crs
  } else {
    # Otherwise, resample the raster to match the first, and add it to the stack
    raster_resampled <- resample(raster_new_crs, raster_stack, method = "near")
    raster_stack <- c(raster_stack, raster_resampled)
  }
}

writeRaster(raster_stack, file.path(here::here('raster_output', 'burn_severity_all.tif')))

# Plot the raster stack
plot(raster_stack, main = "Burn Severity 1984-2021")

```

```{r}
raster_stack <- rast(here::here('raster_output', 'burn_severity_all.tif'))

non_zero_mode <- function(x) {
  x <- x[x != 0]  # Exclude zeros
  if (length(x) == 0) return(0)  # If all values were zero, return zero
  uniqx <- unique(x)
  uniqx[which.max(tabulate(match(x, uniqx)))]
}

# Apply the non-zero mode function to each cell in the raster stack
mode_raster <- app(raster_stack, non_zero_mode)

plot(mode_raster)
```


```{r}
# Load the necessary library
library(terra)

# Define the directory where the raster files are located
raster_dir <- here::here("data", "MTBS_BSmosaics_copy")

# Define the target CRS
target_crs <- "EPSG:3310"

# # Read the raster files
# burn_2020 <- rast(here::here("data", "MTBS_BSmosaics_copy", "mtbs_CA_2020.tif"))
# 
# # Project both rasters to the target CRS
# burn_2020_new_crs <- project(burn_2020, target_crs)

# Get a list of .tif files in the directory
tif_files <- list.files(raster_dir, pattern = "\\.tif$", full.names = TRUE)

# Create an empty raster stack
raster_stack <- rast()

# Loop through the files
for (file_path in tif_files) {
  # Read the raster file
  raster <- rast(file_path)
  
  # Print a message to the console
  message("Processing file: ", tif_files[i])
  
  # Project the raster to the target CRS
  raster_new_crs <- project(raster, target_crs)
  
  # # Resample the raster to a common resolution and extent
  # raster_resampled <- resample(raster_new_crs, raster_stack)
  
  # Combine the resampled raster with the raster stack
  burn_severity_raster_stack <- c(raster_stack, raster_resampled)
}

# Plot the raster stack
plot(burn_severity_raster_stack, main = "Burn Severity 1984-2021")
```


### TEST 1

```{r}
# Load the necessary library
library(terra)

# Define the directory where the raster files are located
raster_dir <- here::here("data", "MTBS_BSmosaics")

# Define the target CRS
target_crs <- "EPSG:3310"

# Create an empty raster stack
raster_stack <- rast()

# Loop through the years from 1988 to 2021
for (year in 2019:2021) {
  # Construct the file path for the raster
  file_path <- file.path(raster_dir, paste0("mtbs_CA_", year, ".tif"))
  
  # Read the raster file
  # raster <- rast(file_path)
  
  # Project the raster to the target CRS
  #raster_new_crs <- project(raster, target_crs)
  
  # Resample the raster to a common resolution and extent
  #raster_resampled <- resample(raster_new_crs, raster_stack)
  
  # Stack the resampled raster onto the raster stack
  #raster_stack <- c(raster_stack, raster_resampled)
  
  # Print a message indicating the current layer
  #message("Processing layer:", year)
}

# Plot the raster stack
plot(raster_stack, main = "Burn Severity 1988-2021")

```


```{r}
# Value	Legend
# 0	Unburnt
# 1	unburnt/low
# 2	low
# 3	moderate
# 4	high
# 5	increased greenness
# 6	masked

# Load the necessary library
library(terra)

# Read the raster files
burn_2020 <- rast(here("data", "MTBS_BSmosaics", "mtbs_CA_2020.tif"))
burn_2021 <- rast(here("data", "MTBS_BSmosaics", "mtbs_CA_2021.tif"))

# Define the target CRS
target_crs <- "EPSG:3310"

# Project both rasters to the target CRS
burn_2020_new_crs <- project(burn_2020, target_crs)
burn_2021_new_crs <- project(burn_2021, target_crs)

# Plot the rasters on top of each other
plot(burn_2020_new_crs, main = 'Burn Severity 2020')

# what is the average burn severity in GDEs vs non GDEs
# trend chart of burn severity in GDEs vs not for each year plot precipitation on top ?

```

# 2020
```{r}
# burn severity 2020 ----
burn_2020 <- rast(here("data", 
                          "MTBS_BSmosaics", 
                          "mtbs_CA_2020.tif"))

target_crs <- "EPSG:3310" # Replace this with the desired CRS

# Project the raster to the new CRS
burn_2020_new_crs <- project(burn_2020, target_crs)

# Check the new CRS
crs(burn_2020_new_crs)

# burn severity 2021 ----
burn_2021 <- rast(here("data", 
                          "MTBS_BSmosaics", 
                          "mtbs_CA_2021.tif")) 

# Resample burn_2021 to match the resolution of burn_2020
burn_2021_resampled <- resample(burn_2021, burn_2020, method = "near")

# Merge the rasters
merged_raster <- merge(burn_2020, 
                   burn_2021_resampled)

stack_raster <- c(burn_2020,
                  burn_2021_resampled)

plot(merged_raster)
plot(stack_raster)
```


# METHOD 1

```{r}
# Load the terra package
library(terra)

# Set the working directory to the folder containing the .tif files
setwd("~/meds/capstone/aquafire/data/MTBS_BSmosaics")

# Get a list of .tif files in the directory
tif_files <- list.files(pattern = "\\.tif$")

rast(tif_files)

# Use a loop to read the .tif files into a list of Raster* objects
raster_list <- list()

for (i in 1:length(tif_files)) {
  raster_list[[i]] <- raster(tif_files[i])
}

plot(raster_list[[1]])
```

```{r}
library(raster)
library(rgdal)

# Set your working directory to the folder containing the .tif files
setwd("~/meds/capstone/aquafire/data/MTBS_BSmosaics")

# List all .tif files in the directory
tif_files <- list.files(pattern = "\\.tif$")

# Read in the .tif files as RasterLayer objects
raster_list <- lapply(tif_files, raster)

# If your files are vector files, you need to convert them to raster files first.
# Load your vector files (e.g., shapefiles) and use the rasterize function.
# Make sure to replace 'YOUR_VECTOR_LAYER' and 'YOUR_RASTER_TEMPLATE' with the actual objects or filenames.
vector_list <- lapply(tif_files, readOGR)
raster_list <- mapply(rasterize, vector_list, raster_list, SIMPLIFY = FALSE)

# Define the target CRS (use the appropriate EPSG code or proj4string)
target_crs <- "+init=epsg:4326"  # WGS 84 (latitude/longitude) as an example

# Reproject each raster in the list to the target CRS
raster_list_reprojected <- lapply(raster_list, function(x) projectRaster(x, crs = target_crs))

# Combine the reprojected rasters into a single raster stack
raster_stack <- stack(raster_list_reprojected)

# Plot the raster stack using the plot function from the raster package
plot(raster_stack)

```

