---
title: "Fire Count Raster"
author: "Jillian Allison"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(raster)
library(rgdal)
library(fasterize)
library(exactextractr)
```

```{r}
# set working directory
setwd(here('~/Desktop/MEDS/Capstone/aquafire'))
```

## Load ecoregions and counties shapefiles 
```{r}
crs_ca <- st_crs(3310)

# Load in ecoregions shapefile
eco_regions <- read_sf(here::here('data', 'ca_eco_l3')) %>% 
  janitor::clean_names()  %>% 
  st_transform(crs_ca) %>% 
  rename(region = us_l3name)

# Read in CA county boundaries
ca_counties <- read_sf(here::here('data', 'CA_Counties')) %>% 
  janitor::clean_names() %>% 
  st_transform(crs_ca) # NAD27 / California Albers
```

## Load fire perimeters data and filter, set CRS, crop to California 
```{r}
fire_perimeters_all <- sf::read_sf(here('data', 
                                        'California_Fire_Perimeters_all')) %>% 
  clean_names() %>% 
  st_transform(crs_ca) %>% # NAD27 / California Albers
  mutate(val = 1) %>% # Create a column containing a value: this means each fire has a value of 1
  filter(year >= 1950) # Filter for only fires after 1950: this is when the dataset becomes reliable. 

# Crop to California
fires_ca <- st_crop(fire_perimeters_all, ca_counties) 
```

## Create an empty raster to use as a template
This valueless raster has a resolution of 30 x 30. We'll be using it to rasterize the fire perimeters layer. 
```{r}
## Set extent
ca_ext <- extent(ca_counties)
## Create valueless raster layer w/ 30 (unit is something) resolution 
ca_rast <- raster(ca_ext, resolution = 30)
crs(ca_rast) <- crs_ca$wkt
```

```{r}
# Use fasterize::fasterize() to convert polygon wildfires to raster layer based on raster template ## FUTURE US: REMEMBER TO CHECK FOR DUPLICATES!!!!! 
fire_count_raster <- fasterize(st_collection_extract(fires_ca, "POLYGON"), ca_rast, field = "val", fun = "sum", background = 0)
# Mask to California's boundary
fire_count_raster_masked <- mask(fire_count_raster, ca_counties) 
#crs(fire_count_raster_masked) <- crs_ca$wkt

# Write raster file
#writeRaster(fire_count_raster_masked, "raster_output/firecount_updated430.tif", overwrite = TRUE)
```



