---
title: "Fire Threat Raster Layer"
author: "Jillian Allison"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(raster)
library(rgdal)
library(fasterize)
library(terra)
```

```{r}
# set working directory
setwd(here('~/Desktop/MEDS/Capstone/aquafire'))
```

## Load ecoregions and counties shapefiles 
```{r}
crs_ca <- st_crs(3310)

# Load in ecoregions shapefile
eco_regions <- read_sf(here::here('data', 'ca_eco_l3')) %>% 
  janitor::clean_names()  %>% 
  st_transform(crs_ca) %>% 
  rename(region = us_l3name)

# Read in CA county boundaries
ca_counties <- read_sf(here::here('data', 'CA_Counties')) %>% 
  janitor::clean_names() %>% 
  st_transform(crs_ca) # NAD27 / California Albers
```

## Create an empty raster to use as a template
This valueless raster has a resolution of 30 x 30. We'll be using it to rasterize the fire perimeters layer. 
```{r}
## Set extent
ca_ext <- extent(ca_counties)
## Create valueless raster layer w/ 30 (unit is something) resolution 
ca_rasterra <- raster(ca_ext, resolution = 30) %>%
  terra::rast()
crs(ca_rasterra) <- crs_ca$wkt 
```

## Load in Fire Threat Raster
```{r}
fire_threat <- raster(here::here("data", "fire_threat.tif")) %>%
  rast() %>%
  terra::project(y = crs_ca$wkt)
  

fire_threat_resampled <- terra::resample(fire_threat, ca_rasterra) # uses nearest neighbors approach for for categorical values 

fire_threat_masked <- mask(fire_threat_resampled, ca_counties)

fire_threat_rasterlayer <- raster(fire_threat_masked)
```

