---
title: "Jillian Capstone"
author: "Jillian Allison"
date: "2023-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
```

## Load Boundaries
```{r}
# Load in ecoregions shapefile
eco_regions <- read_sf(here::here('user','jillian','data', 'ca_eco_l3')) %>% 
  janitor::clean_names()  %>% 
  st_transform("EPSG: 3309") %>% 
  rename(region = us_l3name)

# Read in CA county boundaries
ca_counties <- read_sf(here::here('user','jillian','data', 'CA_Counties')) %>% 
  janitor::clean_names() %>% 
  st_transform("EPSG: 3309") # NAD27 / California Albers

# Filter sb county
sb_county <- ca_counties %>% 
  filter(name == "Santa Barbara")
```

## Load GDE Data
```{r}
# # read in groundwater dependent ecosystem shapefile + clean names
# gde_veg <- read_sf(here('data',
#                         'i02_naturalcommunitiescommonlyassociatedwithgroundwater',
#                         'i02_NCCAG_Vegetation.shp')) %>% 
#   clean_names() %>% 
#   st_transform("EPSG: 3309") # NAD27 / California Albers
# 
# gde_wetlands <- read_sf(here('data','i02_naturalcommunitiescommonlyassociatedwithgroundwater','i02_NCCAG_Wetlands.shp')) %>% 
#   clean_names()  %>% 
#   st_transform("EPSG: 3309") # NAD27 / California Albers
# 
# gde <- st_join(gde_veg, gde_wetlands)
# 
# gde_ndvi <- st_read(here('data', 'i02_NaturalCommunitiesCommonlyAssociatedwithGroundwater_v2_0.gdb')) %>% 
#   st_transform("EPSG: 3309") %>% 
#   clean_names() %>% 
#   st_cast(gde_ndvi, "MULTIPOLYGON")
```

## Load Fire Data
```{r}
fire_perimeters_all <- sf::read_sf(here('user', 
                                        'jillian',
                                        'data', 
                                        'California_Fire_Perimeters_all')) %>% 
  clean_names() %>% 
  st_transform("EPSG: 3309") # NAD27 / California Albers
```

```{r}
fires_sb <- st_crop(fire_perimeters_all, sb_county) %>%
  mutate(val = 1)
```

```{r}
library(raster)
ext <- extent(fires_sb)

r <- raster(ext, resolution = 30) 
crs(r) <- "+init=epsg:3309"
```

```{r}
library(fasterize)
hollister <- fires_sb %>%
  filter(fire_name == "HOLLISTER")

hollister_r <- fasterize(hollister, r)
```

```{r}
testr <- fasterize(st_collection_extract(fires_sb, "POLYGON"), r, field = "val", fun = "sum", background = 0)

POLY <- st_collection_extract(fires_sb, "POLYGON")
```

```{r}
plot(testr)
```

