---
title: "NLCD & Ecoregions, Cropping Raster Layers"
author: "Jillian Allison"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(raster)
library(rgdal)
library(fasterize)
library(FedData)
library(terra)
source("user/jillian/functions/remove_ag_urban.R")
source("user/jillian/functions/raster_to_ecoregions.R")
source("user/jillian/functions/stratified_sample.R")
```

```{r}
# set working directory
setwd(here('~/Desktop/MEDS/Capstone/aquafire'))
```

## Load ecoregions and counties shapefiles 
```{r}
crs_ca <- st_crs(3310)

# Load in ecoregions shapefile
eco_regions <- read_sf(here::here('data', 'ca_eco_l3')) %>% 
  janitor::clean_names()  %>% 
  st_transform(crs_ca) %>% 
  rename(region = us_l3name) %>% 
  mutate(us_l3code = as.numeric(us_l3code))
  

# Read in CA county boundaries
ca_counties <- read_sf(here::here('data', 'California_County_Boundaries', 'cnty19_1.shp')) %>% 
  janitor::clean_names() %>% 
  st_transform(crs_ca) # NAD27 / California Albers
```

## Create an empty raster to use as a template
This valueless raster has a resolution of 30 x 30. We'll be using it to rasterize the fire perimeters layer. 
```{r}
## Set extent
ca_ext <- extent(ca_counties)
## Create valueless raster layer w/ 30 (unit is something) resolution 
ca_rasterra <- raster(ca_ext, resolution = 30) %>%
  terra::rast()
crs(ca_rasterra) <- crs_ca$wkt 
```
### Ecoregions 
```{r}
# Fasterize to rasterize, extent to match others 
eco_region_raster <- fasterize(eco_regions, ca_rast, field = "us_l3code")
```


### Land use data
```{r}
# I'm using the fed data package because NLCD data was in .img format and .... ew 
library(FedData)

nlcd <- FedData::get_nlcd(template = ca_rasterra, year = 2019, label = "ca", dataset = "landcover", landmass = "L48", extraction.dir = "data") %>%
  rast() %>%
  terra::project(y = crs_ca$wkt) # takes several minutes to run, but it will! 


nlcd_resampled <- terra::resample(nlcd, ca_rasterra) # uses nearest neighbors approach for for categorical values 

nlcd_masked <- mask(nlcd_resampled, ca_counties)

nlcd_rasterlayer <- raster(nlcd_masked)

raster::writeRaster(nlcd_rasterlayer, "raster_output/nlcd.tif")

# # plot and view
# plot(nlcd)
# # nlcd_colors() and pal_nlcd() return legend and color palette
# nlcd_colors()
# pal_nlcd()

nlcd_colors()
```




