---
title: "Objects"
author: "Jillian Allison"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(tidyverse)
library(terra)
```

# Functions 
```{r}
source("user/jillian/functions/remove_ag_urban.R")
source("user/jillian/functions/raster_to_ecoregions.R")
source("user/jillian/functions/stratified_sample.R")
source("user/jillian/functions/fire_count_stats.R")
```


# Final Rasters for California
Raster layers masked to CA with ag and urban removed. 
```{r}
fire_count_final <- raster("raster_output/fire_count_final.tif")
tslf_final <- raster("raster_output/tslf_final.tif")
gde_final <- raster("raster_output/gde_final.tif")
nlcd_rasterlayer <- raster("raster_output/nlcd.tif")
fire_threat_final <- raster("raster_output/fire_threat_final.tif")
burn_severity_final <- raster("raster_output/burn_severity_final.tif")

gde_polygons_shiny <- st_read("raster_output/gde_polygons_rm_ag_urb.shp")
gde_summary_shiny <- st_read("raster_output/gde_summary_shiny.shp")
```

# Final Rasters by Ecoregion 
Raster layers by eco region with ag and urban removed. 
## GDEs
```{r}
gde_1 <- raster("raster_output/gde_1.tif")
gde_4 <- raster("raster_output/gde_4.tif")
gde_5 <- raster("raster_output/gde_5.tif")
gde_6 <- raster("raster_output/gde_6.tif")
gde_7 <- raster("raster_output/gde_7.tif")
gde_8 <- raster("raster_output/gde_8.tif")
gde_9 <- raster("raster_output/gde_9.tif")
gde_13 <- raster("raster_output/gde_13.tif")
gde_14 <- raster("raster_output/gde_14.tif")
gde_78 <- raster("raster_output/gde_78.tif")
gde_80 <- raster("raster_output/gde_80.tif")
gde_81 <- raster("raster_output/gde_81.tif")
gde_85 <- raster("raster_output/gde_85.tif")
```


## Fire Count
```{r}
fire_count_1 <- raster("raster_output/fire_count_1.tif")
fire_count_4 <- raster("raster_output/fire_count_4.tif")
fire_count_5 <- raster("raster_output/fire_count_5.tif")
fire_count_6 <- raster("raster_output/fire_count_6.tif")
fire_count_7 <- raster("raster_output/fire_count_7.tif")
fire_count_8 <- raster("raster_output/fire_count_8.tif")
fire_count_9 <- raster("raster_output/fire_count_9.tif")
fire_count_13 <- raster("raster_output/fire_count_13.tif")
fire_count_14 <- raster("raster_output/fire_count_14.tif")
fire_count_78 <- raster("raster_output/fire_count_78.tif")
fire_count_80 <- raster("raster_output/fire_count_80.tif")
fire_count_81 <- raster("raster_output/fire_count_81.tif")
fire_count_85 <- raster("raster_output/fire_count_85.tif")
```

## TSLF 
```{r}
tslf_1 <- raster("raster_output/tslf_1.tif")
tslf_4 <- raster("raster_output/tslf_4.tif")
tslf_5 <- raster("raster_output/tslf_5.tif")
tslf_6 <- raster("raster_output/tslf_6.tif")
tslf_7 <- raster("raster_output/tslf_7.tif")
tslf_8 <- raster("raster_output/tslf_8.tif")
tslf_9 <- raster("raster_output/tslf_9.tif")
tslf_13 <- raster("raster_output/tslf_13.tif")
tslf_14 <- raster("raster_output/tslf_14.tif")
tslf_78 <- raster("raster_output/tslf_78.tif")
tslf_80 <- raster("raster_output/tslf_80.tif")
tslf_81 <- raster("raster_output/tslf_81.tif")
tslf_85 <- raster("raster_output/tslf_85.tif")
```

## Fire Threat
```{r}
fire_threat_1 <- raster("raster_output/fire_threat_1.tif")
fire_threat_4 <- raster("raster_output/fire_threat_4.tif")
fire_threat_5 <- raster("raster_output/fire_threat_5.tif")
fire_threat_6 <- raster("raster_output/fire_threat_6.tif")
fire_threat_7 <- raster("raster_output/fire_threat_7.tif")
fire_threat_8 <- raster("raster_output/fire_threat_8.tif")
fire_threat_9 <- raster("raster_output/fire_threat_9.tif")
fire_threat_13 <- raster("raster_output/fire_threat_13.tif")
fire_threat_14 <- raster("raster_output/fire_threat_14.tif")
fire_threat_78 <- raster("raster_output/fire_threat_78.tif")
fire_threat_80 <- raster("raster_output/fire_threat_80.tif")
fire_threat_81 <- raster("raster_output/fire_threat_81.tif")
fire_threat_85 <- raster("raster_output/fire_threat_85.tif")
```

## Burn Severity
```{r}
burn_severity_1 <- raster("raster_output/burn_severity_1.tif")
burn_severity_4 <- raster("raster_output/burn_severity_4.tif")
burn_severity_5 <- raster("raster_output/burn_severity_5.tif")
burn_severity_6 <- raster("raster_output/burn_severity_6.tif")
burn_severity_7 <- raster("raster_output/burn_severity_7.tif")
burn_severity_8 <- raster("raster_output/burn_severity_8.tif")
burn_severity_9 <- raster("raster_output/burn_severity_9.tif")
burn_severity_13 <- raster("raster_output/burn_severity_13.tif")
burn_severity_14 <- raster("raster_output/burn_severity_14.tif")
burn_severity_78 <- raster("raster_output/burn_severity_78.tif")
burn_severity_80 <- raster("raster_output/burn_severity_80.tif")
burn_severity_81 <- raster("raster_output/burn_severity_81.tif")
burn_severity_85 <- raster("raster_output/burn_severity_85.tif")
```


# Quick Plots 
```{r}
# Read in CA boundary
ca <- read_sf(here::here('data', 'ca-state-boundary', 'CA_State_TIGER2016.shp')) %>% 
  janitor::clean_names() %>% 
  st_transform(crs_ca) # NAD27 / California Albers
```

```{r}
dev.off()
plot(tslf_final, axes = FALSE, box = FALSE)
plot(ca, add = TRUE, col = "transparent")
title(main = "Time Since Last Burn (Years)")
```

```{r}
dev.off()
plot(fire_count_final, axes = FALSE, box = FALSE)
plot(ca, add = TRUE, col = "transparent")
title(main = "Fire Count Since 1950")
```

```{r}
dev.off()
plot(gde_final, axes = FALSE, box = FALSE, legend = FALSE)
plot(ca, add = TRUE, col = "transparent")
title(main = "Groundwater Dependent Ecosystems in California")
```




