---
title: "Wade Capstone"
author: "Wade Sedgwick"
date: "2023-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(tmap)
library(rmapshaper)
library(stars)
library(terra)
library(raster)
library(rgdal)
```

```{r}
# set working directory
setwd(here('~/Desktop/bren_meds/courses/capstone/aquafire/data'))
```

## Load Boundaries
```{r}
# Load in ecoregions shapefile
eco_regions <- read_sf(here::here('data', 'ca_eco_l3', 'ca_eco_l3.shp')) %>% 
  janitor::clean_names()  %>% 
  st_transform("EPSG: 3309") %>% 
  rename(region = us_l3name)

# Read in CA county boundaries
ca_counties <- read_sf(here::here('data', 'CA_Counties', 'CA_Counties_TIGER2016.shp')) %>% 
  janitor::clean_names() %>% 
  st_transform("EPSG: 3309") # NAD27 / California Albers

# Filter sb county
sb_county <- ca_counties %>% 
  filter(name == "Santa Barbara")
```

## Load GDE Data
```{r}
veg_layer <- st_read(dsn = here('data', 'i02_NaturalCommunitiesCommonlyAssociatedwithGroundwater_v2_0.gdb'),
                     layer = 'i02_NCCAG_Vegetation_2_0') %>% 
  st_transform("EPSG: 3309")

wetland_layer <- st_read(dsn = here('data', 'i02_NaturalCommunitiesCommonlyAssociatedwithGroundwater_v2_0.gdb'),
                     layer = 'i02_NCCAG_Wetlands_2_0')





# # read in groundwater dependent ecosystem shapefile + clean names
# gde_veg <- read_sf(here('data',
#                         'i02_naturalcommunitiescommonlyassociatedwithgroundwater',
#                         'i02_NCCAG_Vegetation.shp')) %>%
#   clean_names() %>%
#   st_transform("EPSG: 3309") # NAD27 / California Albers
# 
# gde_wetlands <- read_sf(here('user', 'wade', 'data','i02_naturalcommunitiescommonlyassociatedwithgroundwater','i02_NCCAG_Wetlands.shp')) %>%
#   clean_names()  %>%
#   st_transform("EPSG: 3309") # NAD27 / California Albers
# 
# gde <- st_join(gde_veg, gde_wetlands)
# 
# gde_ndvi <- st_read(here('data', 'i02_NaturalCommunitiesCommonlyAssociatedwithGroundwater_v2_0.gdb')) %>%
#   st_transform("EPSG: 3309") %>%
#   clean_names() %>%
#   st_cast(gde_ndvi, "MULTIPOLYGON")

test <- st_read(here('user', 'wade', 'data', 'gdes', 'Groundwater_dependent_ecosystems_summary.shp'))

```

## Load Fire Data
```{r}
fire_perimeters_all <- sf::read_sf(here('user', 'wade', 'data', 'California_Fire_Perimeters_all', 'California_Fire_Perimeters_all.shp')) %>% 
  clean_names() %>% 
  st_transform("EPSG: 3309") # NAD27 / California Albers
```


```{r}
class(ca_counties)
class(eco_regions)
class(fire_perimeters_all)

head(ca_counties)
head(eco_regions)

tm_shape(eco_regions) +
  tm_polygons()

head(fire_perimeters_all$gis_acres)

median(fire_perimeters_all$gis_acres)



fire_perimeters <- fire_perimeters_all %>% filter(gis_acres > 20000)

fire_perimeters_simp <- ms_simplify(fire_perimeters, keep = 0.05)
counties_simp <- ms_simplify(ca_counties, keep = 0.05)

tm_shape(counties_simp) +
  tm_borders() +
  tm_shape(fire_perimeters_simp) +
  tm_fill(col = "gis_acres")


fire_perimeters_raster <- st_rasterize(fire_perimeters_simp)

tm_shape(counties_simp) +
  tm_borders() +
  tm_shape(b) +
  tm_raster(col = "gis_acres")

```

To do - filter by county and do overlap of wildfires for just GDEs in SBC


```{r}
sb_county <- ca_counties %>% clean_names() %>% filter(name == "Santa Barbara")
sb_county
tm_shape(sb_county) +
  tm_polygons()

fire_sb_county <- st_filter(fire_perimeters_simp, sb_county)

tm_shape(fire_sb_county) +
  tm_polygons(alpha = 0.9)
  tm_shape(sb_county) +
  tm_fill(alpha = 0.3)
  
test

# Extracting values - chatGPT
raster_layer <- raster(extent(fire_perimeters_simp), crs = st_crs(fire_perimeters_simp))
raster_layer <- rasterize(fire_perimeters_simp, raster_layer)

year_layer <- raster_layer
year_layer[] <- apply(st_extract(st_as_sf(year_layer), fire_perimeters_simp, "max"), 1, max)

fire_perimeters_raster
tslb <- st_extract(fire_perimeters_raster, fire_perimeters_simp)

# ----
class(fire_perimeters_simp)
raster_layer <- raster(extent(fire_perimeters_simp), crs = st_crs(fire_perimeters_simp))
raster_layer[] <- rasterize(fire_perimeters_simp, raster_layer, field = "year")

tm_shape(raster_layer) +
  tm_raster()


class(tslb)

tm_shape(tslb) +
  tm_polygons()

```

### Modeled fire threat layer attempt

```{r}

fire_threat <- st_read(dsn = here('data', 'fthrt14_2-1.gdb'))


a <- fasterize::fasterize("/Users/wsedgwick/Desktop/bren_meds/courses/capstone/aquafire/data/fthrt14_2-1.gdb/fras_blk_fthrt14_2")

class(fire_threat)

my_data <- readOGR(dsn = "/Users/wsedgwick/Desktop/bren_meds/courses/capstone/aquafire/data", layer = "fthrt14_2-1.gdb")

# below is able to read first layer, but not all and it is not saved
my_data <- readOGR("fthrt14_2-1.gdb")

my_data <- readOGR(dsn = "/Users/wsedgwick/Desktop/bren_meds/courses/capstone/aquafire/data/fthrt14_2-1.gdb", layer = "a0000000a.gdbtable")

# tried with st_read
c <- st_read("/Users/wsedgwick/Desktop/bren_meds/courses/capstone/aquafire/data/fthrt14_2-1.gdb", layer = "fras_blk_fthrt14_2")

# was able to read it in as a SpatVector and Terra object, but it has no geometries
a <- vect("/Users/wsedgwick/Desktop/bren_meds/courses/capstone/aquafire/data/fthrt14_2-1.gdb", layer = "fras_blk_fthrt14_2")

# tried with raster::raster
a <- rasterize("/Users/wsedgwick/Desktop/bren_meds/courses/capstone/aquafire/data/fthrt14_2-1.gdb/fras_blk_fthrt14_2")

# tried with terra::rast
a <- rast("/Users/wsedgwick/Desktop/bren_meds/courses/capstone/aquafire/data/fthrt14_2-1.gdb/a0000000a.gdbtable")

plot(a$rasterband_id)

tm_shape(a$rasterband_id) +
  tm_polygons()

a <- st_layers("/Users/wsedgwick/Desktop/bren_meds/courses/capstone/aquafire/data/fthrt14_2-1.gdb/fras_blk_fthrt14_2")

a <- st_drivers(what = "raster")

plot(a)
class(a$block_key)

head(a)

str(a)

```



