---
title: "Andre Capstone"
author: "Andre Dextre"
date: "2023-03-15"
output: html_document
---

## Load Libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(sf)
library(readxl)
library(tmap)
library(stars)
library(ggplot2)
library(mapview)
```

## Read In Wildfire Paremeter Data 

```{r}
#Load data
cali <- read_sf(here("data", "CA_Boundaries")) %>%
  clean_names()

wf_perimeter <- read_sf(here("data", "California_Fire_Perimeters"))

#california <- tigris::counties("CA")

wf_fire <- ggplot() +
  geom_sf(data = wf_parameter,
          fill = 'red',
          col = 'yellow',
          lwd = 0.1) +
    coord_sf() +
    geom_sf(data = cali,
          fill = NA,
          col = 'black',
          lwd = 0.1) +
  theme_void()

wf_fire
```

```{r}
grid = st_as_stars(st_bbox(cali), dx = 30000, dy = 30000)
grid = st_as_sf(grid) # convert grid to polygon
grid = grid[cali, ] # crop grid to cali polygon

plot(st_geometry(grid), axes = TRUE, reset = FALSE) # plot the grid
plot(st_geometry(wf_parameter), border = "red", add = TRUE)
```
